apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxrs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginxapp
  template:
    metadata:
      name: nginxpod
      labels:
        name: nginxapp

    spec:
      containers:
      - image: nginx
        name: nginxcontainer
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: replicasetsvc
spec:
  selector:
    name: nginxapp
  type: NodePort
  ports:
  - name: nginxport
    port: 80
    targetPort: 80
