apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginsds
spec:
  selector:
    matchLabels:
      name: nginxapp
  template:
    metadata:
      name: nginxpod
      labels:
        name: nginxapp

    spec:
      containers:
      - image: nginx:1.14.2
        name: nginxcontainer
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: daemonsetsvc
spec:
  selector:
    name: nginxapp
  type: NodePort
  ports:
  - name: nginxport
    port: 80
    targetPort: 80
