apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 5
  template:
    metadata:
      name: nginxpod
      labels:
        name: nginxapp
    spec:
       containers:
       - name: nginxcontainer
         image: nginx
         ports:
         - containerPort: 80
